#!/usr/bin/env bash
# snapshot.sh — single-command full system state report.
# Composes every existing monitor into one consolidated output. The "what's
# the brain doing right now" view. Safe to run any time, ~5s wall.
set -u

OUT="${1:-/dev/stdout}"

{
  echo "# Brain snapshot — $(date)"
  echo "Host: $(hostname) · User: $(whoami) · Uptime: $(uptime | awk -F'up ' '{print $2}' | awk -F',' '{print $1}')"
  echo

  echo "## Routing layer"
  if [ -f "$HOME/dotfiles/claude/CLAUDE.md" ]; then
    lines=$(wc -l <"$HOME/dotfiles/claude/CLAUDE.md")
    agents=$(find "$HOME/dotfiles/claude/agents/" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
    skill_count=$(find "$HOME/dotfiles/claude/skills/" -maxdepth 1 -mindepth 1 2>/dev/null | wc -l | tr -d ' ')
    echo "- CLAUDE.md: $lines lines"
    echo "- Custom agents: $agents · Skills: $skill_count"
  else
    echo "- 🔴 CLAUDE.md missing"
  fi
  echo

  echo "## Knowledge layers"
  for layer in wiki design tel; do
    dir=$(readlink -f "$HOME/.claude/$layer" 2>/dev/null || echo "$HOME/.claude/$layer")
    if [ -d "$dir" ]; then
      count=$(find "$dir" -type f \( -name "*.md" -o -name "*.yaml" -o -name "*.py" -o -name "*.sh" \) -not -path "*/.venv/*" -not -path "*/__pycache__/*" 2>/dev/null | wc -l | tr -d ' ')
      echo "- $layer/: $count files"
    else
      echo "- 🔴 $layer/: missing"
    fi
  done
  echo

  echo "## Hooks (sourced from ~/dotfiles/claude/hooks/)"
  if [ -d "$HOME/dotfiles/claude/hooks" ]; then
    n=$(find "$HOME/dotfiles/claude/hooks/" -maxdepth 1 -name "*.sh" 2>/dev/null | wc -l | tr -d ' ')
    extra=$(find "$HOME/.claude/hooks/" -maxdepth 1 -name "*.sh" 2>/dev/null | wc -l | tr -d ' ')
    echo "- dotfiles hooks: $n · ~/.claude additional: $extra"
  fi
  echo

  echo "## Cron agents (launchd)"
  loaded=$(launchctl list 2>/dev/null | grep -c "bio.claude")
  total_plists=$(find "$HOME/dotfiles/claude/launchd/" -maxdepth 1 -name "*.plist" 2>/dev/null | wc -l | tr -d ' ')
  echo "- Loaded: $loaded · Plists in dotfiles: $total_plists"
  if [ "$loaded" -lt "$total_plists" ]; then
    echo "  🟡 some plists may not be loaded — check launchctl list | grep bio.claude"
  fi
  echo

  echo "## MCP servers"
  if command -v claude >/dev/null 2>&1; then
    list=$(claude mcp list 2>/dev/null | grep -E ".*-.*(✓ Connected|! Needs|✗)")
    mcp_total=$(echo "$list" | grep -c .)
    mcp_ok=$(echo "$list" | grep -c "✓ Connected")
    mcp_bad=$((mcp_total - mcp_ok))
    echo "- Total: $mcp_total · Connected: $mcp_ok · Disconnected/needs-auth: $mcp_bad"
    if [ "$mcp_bad" -gt 0 ]; then
      echo "$list" | grep -v "✓ Connected" | head -3 | sed 's/^/  🟡 /'
    fi
  else
    echo "- 🔴 claude CLI not on PATH"
  fi
  echo

  echo "## TEL"
  if [ -x "$HOME/.claude/scripts/tel-canary.sh" ]; then
    "$HOME/.claude/scripts/tel-canary.sh" 2>&1 | sed 's/^/- /'
    if curl -fsS -m 2 http://127.0.0.1:8765/health >/dev/null 2>&1; then
      svc=$(curl -fsS -m 2 http://127.0.0.1:8765/health | jq -r '.services | join(",")' 2>/dev/null)
      echo "- ✓ daemon LIVE · services: $svc"
    elif [ -L "$HOME/Library/LaunchAgents/bio.tel.plist" ] || [ -f "$HOME/Library/LaunchAgents/bio.tel.plist" ]; then
      echo "- 🔴 daemon plist installed but not responding"
    else
      echo "- 🟡 daemon not yet activated (see ~/.claude/tel/ops/INSTALL.md)"
    fi
  fi
  echo

  echo "## Telemetry"
  if [ -n "${LANGFUSE_BASE_URL:-}" ]; then
    if curl -fsS -m 2 "${LANGFUSE_BASE_URL}/api/public/health" >/dev/null 2>&1; then
      ver=$(curl -fsS -m 2 "${LANGFUSE_BASE_URL}/api/public/health" | jq -r .version 2>/dev/null)
      echo "- ✓ Langfuse $ver responding at $LANGFUSE_BASE_URL"
    else
      echo "- 🔴 Langfuse unreachable at $LANGFUSE_BASE_URL"
    fi
  else
    echo "- 🟡 LANGFUSE_BASE_URL unset"
  fi
  echo

  echo "## Memory"
  mem_dir="$HOME/.claude/projects/-Users-leonardofibonacci-Claude-Code/memory"
  if [ -f "$mem_dir/MEMORY.md" ]; then
    mem_lines=$(wc -l <"$mem_dir/MEMORY.md")
    mem_files=$(find "$mem_dir" -maxdepth 1 -name "*.md" | wc -l | tr -d ' ')
    echo "- MEMORY.md: $mem_lines/200 lines · files: $mem_files"
  fi
  echo

  echo "## Dotfiles git status"
  if [ -d "$HOME/dotfiles/.git" ]; then
    cd "$HOME/dotfiles" && {
      ahead=$(git rev-list --count origin/main..HEAD 2>/dev/null || echo 0)
      dirty=$(git status --short | wc -l | tr -d ' ')
      echo "- $ahead commit(s) ahead of origin · $dirty file(s) dirty"
    }
  fi
  echo

  echo "## Recent self-monitor reports"
  for r in mcp-probe drift memory-health digest skill-usage session-candidates; do
    latest=$(find "$HOME/.claude/audits/" -maxdepth 1 -name "$r-*.md" -type f 2>/dev/null | sort -r | head -1)
    [ -n "$latest" ] && echo "- $(basename "$latest")"
  done
  echo

  echo "_Generated by ~/.claude/scripts/snapshot.sh_"
} >"$OUT"
